# Generated by Django 3.2 on 2022-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookptsession',
            name='staff',
            field=models.CharField(choices=[('stf.username', 'stf.username'), ('stf.username', 'stf.username'), ('stf.username', 'stf.username')], default='karen', max_length=15),
        ),
    ]
