# Generated by Django 3.2 on 2022-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_bookings', '0002_bookptsession_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookptsession',
            name='staff',
            field=models.CharField(choices=[('admin', 'admin'), ('steve', 'steve'), ('karen', 'karen')], default='karen', max_length=15),
        ),
    ]
