# Generated by Django 3.2 on 2022-04-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_bookings', '0002_alter_bookptsession_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookptsession',
            name='staff',
            field=models.CharField(choices=[('Steve', 'Steve')], default='karen', max_length=15),
        ),
    ]
